#!/bin/bash -e
# Arguments
# 1. Executable file
# 2. New Root Path
if test $# -lt 2; then
echo "eg. $0  ExecutableFile(fullpath) NewRootPath"
exit
fi

EXECFILE=$1
NEWROOT=$2

test -L "$EXECFILE" && echo "$EXECFILE is a symbolic link" && exit 1
! test -e "$EXECFILE" && echo "$EXECFILE does not exist" && exit 1
file "$EXECFILE"|grep -iq "shell script" && echo "$EXECFILE is a shell script" && exit 1

set +e
r_ldd=$(ldd "$EXECFILE")
RET=$?
set -e
[ $RET -gt 1 ] && exit $RET

if ! test -d "$NEWROOT"; then
echo "$NEWROOT does not exist"
exit
fi

echo "$r_ldd" | while read i
do
	fpath="${i#* => }"
	fpath="${fpath%% *}"
	[[ $fpath =~ ^/ ]] || continue
	[[ -e "${NEWROOT}${fpath}" ]] && continue

	echo " += $fpath"
	echo $fpath | cpio -pdm ${NEWROOT}

	while [ -L "$fpath" ]
	do
		dirn=$(dirname "$fpath")
		lnk=$(readlink "$fpath")
		ldir=$(dirname "$lnk")
		if [[ $ldir =~ ^/ ]]; then
			fpath="$lnk"
		else
			fpath="$dirn/$lnk"
		fi
		[[ -e "${NEWROOT}${fpath}" ]] && break
		echo $fpath | cpio -pdm ${NEWROOT}
	done
done

#set -x
echo $EXECFILE | cpio -pdm ${NEWROOT}
#set +x
