#!/bin/sh

usage() {
	echo "  Usage: iwscan [wlan-ifname]"
	exit
}

wlifs=$(ip addr show | \
	sed -ne 's/^[1-9][0-9]*: \(w.\+\): <.*BROADCAST.\+$/\1/p')

if [ -z "$wlifs" ]; then
	echo " no wlan interface"
	exit
fi

if [ $# -ge 1 ]; then
	echo $wlifs | grep -q -w "$1" && wlif="$1"
	if [ -z $wlif ]; then
		echo " not exist"
		usage
	fi
else
	wlif=$(echo $wlifs | cut -d ' ' -f 1)
fi

set -e
iwconfig $wlif txpower auto
sleep 0.2
ip link set dev $wlif up
set +e


p_1st=1

wl_print() {
	if [ $p_1st -gt 0 ]; then
		p_1st=0
		echo \
"AP-MAC              CH  PWR  ENC    SSID"
#         1         2         3         4
#12345678901234567890123456789012345678901234567890
	fi

	case "$w_encr" in
	 0) secu="OPN"	;;
	 1) secu="WPA"	;;
	 2) secu="WPA2"	;;
	 3) secu="WPA3"	;;
	 8) secu="WEP"	;;
	 *) secu=""	;;
	esac

	printf "%-17s  %3s  %3s  %-4s   %-8s\n" \
		"$w_mac" "$w_chnl" "$w_sgnl" "$secu" "$w_ssid"
}


IFS=$'\n'

nxt=0

iw dev $wlif scan | while read -r line; do

  if echo "$line" | grep -q -E '^BSS [0-9a-f]{2}(:[0-9a-f]{2}){5}'; then
    if [ $nxt -gt 0 ]; then
      wl_print
    fi
    w_mac=$(echo "$line" | \
            sed -ne 's/^BSS \([0-9a-f]\{2\}\(:[0-9a-f]\{2\}\)\{5\}\).*$/\1/p')
    nxt=1
    continue
  fi

  case $nxt in

   1)
    if echo "$line" | grep -q -E '^[[:space:]]+capability: '
    then
      if echo "$line" | grep -q -i -w Privacy; then
        w_encr=8
      else
        w_encr=0
      fi
      nxt=2
    fi
    ;;

   2)
    if echo "$line" | \
		grep -q -E '^[[:space:]]+signal: .{0,1}[0-9]{2}\.[0-9]+ dBm'
    then
      w_sgnl=$(echo "$line" | sed -ne \
		's/^[[:space:]]*signal: \(.\{0,1\}[0-9]\{2\}\)\..*$/\1/p')
      nxt=3
    fi
    ;;

   3)
    if echo "$line" | grep -q -E '^[[:space:]]+SSID: '
    then
      w_ssid=$(echo "$line" | sed -ne 's/^[[:space:]]*SSID: \(.*\)$/\1/p')
      nxt=4
    fi
    ;;

   4)
    if echo "$line" | \
		grep -q -E '^[[:space:]]+DS Parameter set: channel [0-9]{1,3}$'
    then
      w_chnl=$(echo "$line" | sed -ne \
		's/^[[:space:]]*DS Parameter set: channel \([0-9]\+\)$/\1/p')
      if [ $w_encr -gt 0 ]; then
        nxt=5
      else
        nxt=9
      fi
    fi
    ;;

   5)
    if echo "$line" | grep -q -E '^[[:space:]]+RSN:[[:space:]]+\* Version: 1$'
    then
      nxt=6
    elif echo "$line" | \
		grep -q -E '^[[:space:]]+WPA:[[:space:]]+\* Version: 1$'
    then
      w_encr=1
      nxt=9
    fi
    ;;

   6)
    if echo "$line" | grep -q -E '^[[:space:]]+\* Authentication suites: '
    then
      if echo "$line" | grep -q -w SAE; then
        w_encr=3
      else
        w_encr=2
      fi
      nxt=9
    fi
    ;;

  esac

  if [ $nxt -ge 9 ]; then
    wl_print
    nxt=0
  fi

done
